# Generated by Django 2.2.1 on 2019-05-01 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=85)),
                ('country', models.CharField(blank=True, max_length=85)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('latitude', models.DecimalField(blank=True, decimal_places=3, max_digits=6)),
                ('longitude', models.DecimalField(blank=True, decimal_places=4, max_digits=8)),
            ],
            options={
                'verbose_name_plural': 'cities',
            },
        ),
    ]
