# Generated by Django 2.2.1 on 2019-05-02 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_city_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('name', 'country_code')},
        ),
    ]
