# Generated by Django 2.2.1 on 2019-05-02 15:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('weather', '0004_auto_20190502_0432'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='user',
            field=models.ManyToManyField(related_name='my_cities', to=settings.AUTH_USER_MODEL),
        ),
    ]
